---
- hosts: cloud 
  become: true
  vars:
  - sshkeypath: '~/.ssh/linode.pub'
  
  vars_prompt:
  - name: "username"
    prompt: "What is your username?"
    private: false

  - name: password
    prompt: Enter the password
    private: true
    encrypt: sha512_crypt
    confirm: true
    salt_size: 7

  - name: "new_hostname"
    prompt: "What is your hostname?"
    private: false

  tasks:
  - name: Add a new user
    user:
     name: "{{ username }}"
     shell: /bin/bash
     password: "{{ password | password_hash('sha512') }}"
  - name: update hostnames
    hostname:
      name: "{{ new_hostname }}"
  - name: Add user to the sudoers
    copy:
     dest: "/etc/sudoers.d/{{ username }}"
     content: "{{ username }}  ALL=(ALL)  NOPASSWD: ALL"
  - name: Deploy SSH Key
    authorized_key: user="{{ username }}"
                    key="{{ lookup('file', "{{ sshkeypath }}") }}"
                    state=present

  - name: Update SSH configuration to be more secure (thanks Jeff!)
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
      validate: 'sshd -T -f %s'
      mode: 0644
    with_items:
      - regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
      - regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
      - regexp: "^UseDNS"
        line: "UseDNS no"
      - regexp: "^PermitEmptyPasswords"
        line: "PermitEmptyPasswords no"
      - regexp: "^ChallengeResponseAuthentication"
        line: "ChallengeResponseAuthentication no"
      - regexp: "^GSSAPIAuthentication"
        line: "GSSAPIAuthentication no"
      - regexp: "^X11Forwarding"
        line: "X11Forwarding no"
    notify: restart ssh

     
  - name: Install packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - wget
      - neovim
      - tree
      - neofetch
      - zsh
      - lsb-release
      - unzip
      - bat
      - exa
      - ca-certificates
      - curl
      - gnupg
      - fonts-hack
      - git
      - htop
      - software-properties-common


# *** Oh-My-zsh ***

  - name: Installing Oh-My-zsh
    become: yes
    become_user: '{{ username }}'
    command: sh -c 'curl -fsL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash'

  - name: Changing Default Shell to ZSH
    become: yes
    user: 
      name: '{{ username }}'
      shell: /bin/zsh 

  - name: Changing Default ZSH Theme to Agnoster
    lineinfile:
      path: '/home/{{ username }}/.zshrc'
      regexp: '^ZSH_THEME='
      line: 'ZSH_THEME="agnoster"'

  - name: Creating ZSH Completion folder
    file:
      path: '/home/{{ username }}/.oh-my-zsh/completions'
      state: directory
      mode: 0755

  - name: Adding autoload to compinit
    lineinfile:
      path: '/home/{{ username }}/.zshrc'
      line: 'autoload -U compinit && compinit'
      state: present

  - name: ZSH alias
    lineinfile: 
      path: "/home/{{ username }}/.zshrc"
      line: "alias vim='nvim'\nalias ls='exa --icons --sort=type'\nalias cat='batcat'"  
      state: present

# *** Dotfiles ***  

  - name: Delete all dotfiles
    file:
      path: "/home/{{ username}}/.config"
      state: absent    

  - name: Clone a github repository dotfiles
    git:
      repo: https://github.com/Bramba7/dotfiles.git 
      dest: /home/{{ username }}/.config
      clone: yes
      update: yes

# *** Nvim ***

  - name: Dow vm-plug
    become: yes
    become_user: '{{ username }}'
    command: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
 
  - name: Install vm-plug
    become: yes
    become_user: '{{ username }}'
    command: nvim +'PlugInstall --sync' +qa

# *** Docker ***

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/{{ ansible_distribution| lower }}/gpg
      state: present
    when: ansible_os_family == "Debian"

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution| lower }} {{ ansible_distribution_release }} stable
      state: present
    when: ansible_os_family == "Debian"
    
  - name: Install docker and its dependencies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:   
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
      - docker-buildx-plugin 
      - docker-compose-plugin
    when: ansible_os_family == "Debian"

  - name: Add user to docker group
    user:
      name: "{{ username }}"
      group: docker
    notify:
      - docker status
    
  - name: Print a message
    ansible.builtin.debug:
      msg: 'ssh {{ username }}@{{ ansible_ssh_host }}'
  
  handlers:
  - name: docker status
    service: 
      name: docker 
      state: started

  - name: restart ssh
    service: 
      name: sshd 
      state: restarted
